apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-deployment
  labels:
    app: payment-service
    profile: prod
spec:
  selector:
    matchLabels:
      app: payment-service
      profile: prod
  # 앱이 Ready 상태가 될 때까지 기다리는 시간
  minReadySeconds: 10
  # 롤링 업데이트:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      # 롤링 업데이트시 스케일아웃할 최대 pod 수
      maxSurge: 1
      maxUnavailable: 0
  replicas: 1
  template:
    metadata:
      name: payment-pod
      labels:
        app: payment-service
        profile: prod
    spec:
      containers:
        - name: payment-service
          image: ${ECR_REGISTRY}/${AWS_ECR_REPOSITORY}:${IMAGE_TAG}
          imagePullPolicy: IfNotPresent
        - name: mysql
          image: mysql:8.0.34
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "11111111"
            - name: MYSQL_DATABASE
              value: payment-service
          resources:
            requests:
              memory: "1Gi"
          volumeMounts:
            - name: lotdiz-payment-storage
              mountPath: /var/lib/mysql
            - name: mysql-config
              mountPath: /etc/mysql/conf.d
      volumes:
        - name: lotdiz-payment-storage
          persistentVolumeClaim:
            claimName: payment-efs-claim
        - name: mysql-config
          configMap:
            name: mysql-config
      restartPolicy: Always

