apiVersion: v1
kind: PersistentVolume
metadata:
  name: payment-efs-volume
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: "payment-efs-sc"
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-044cc40835d82aa84