apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: payment-efs-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "payment-efs-sc"
  resources:
    requests:
      storage: 5Gi